#!/bin/sh
### BEGIN INIT INFO
# Provides:	secretmanager
# Required-Start: $all
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: secretserver
# Description: Demarre et arrete le SecretServer. Composant de securite du SecretManager.
### END INIT INFO

cd /var/www/SecretManager

case $1 in
 start)
	echo "Starting SecretServer "
	cd /var/www/SecretManager
	php SM-secrets-server.php 2>&1 > /var/tmp/SecretServer.log &	
	;;
 stop)
	echo "Stopping SecretServer "
	PID=`ps aux|grep "php SM-secrets-server"|grep -v grep|awk '{print $2}'`
	kill -15 $PID
	;;
 *)
	echo "Usage: /etc/init.d/SecretManager.sh {start|stop}"
	exit 1
	;;
esac

exit 0
